name: Set Up VPC and ECR

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options:
          - create
          - destroy
        description: Select the action, whether to create or destroy VPC and ECR

jobs:
  setup-job:
    runs-on: ubuntu-latest
    name: "Running ${{ inputs.action }} - VPC and ECR"
    defaults:
      run:
        working-directory: terraform-setup

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform ${{ inputs.action }}
        run: |
          if [ "${{ inputs.action }}" = "create" ]; then
            terraform apply --auto-approve
          elif [ "${{ inputs.action }}" = "destroy" ]; then
            terraform destroy --auto-approve
          fi
